// Write prisma/schema.local.prisma: the deployed schema with its datasource
// pointed at SQLite, for local development.
//
// prisma/schema.prisma is production truth and says postgresql. Prisma will not
// take a provider from an env var, so the alternative to this file is either a
// second schema that drifts from the first or a line every developer edits and
// eventually commits by accident — which is exactly how a SQLite provider ends
// up in a deploy.
//
//   npm run db:local     regenerate the local schema + client
//   npx prisma db push --schema prisma/schema.local.prisma
//
// The generated file is gitignored. Regenerate it after any schema change.
import { readFileSync, writeFileSync } from "node:fs";

const SOURCE = "prisma/schema.prisma";
const TARGET = "prisma/schema.local.prisma";

const schema = readFileSync(SOURCE, "utf8");
if (!/provider\s*=\s*"postgresql"/.test(schema)) {
  console.error(`${SOURCE} no longer declares postgresql — check it before deploying.`);
  process.exit(1);
}

writeFileSync(
  TARGET,
  "// GENERATED by scripts/local-schema.mjs from prisma/schema.prisma. Do not edit.\n" +
    "// Local development only: same models, SQLite instead of Postgres.\n" +
    schema.replace(/provider\s*=\s*"postgresql"/, 'provider = "sqlite"'),
  "utf8"
);
console.log(`wrote ${TARGET} (sqlite)`);
